CREATE SCHEMA IF NOT EXISTS stg;

CREATE SCHEMA IF NOT EXISTS dwh;

DROP TABLE IF EXISTS stg.employee;

CREATE TABLE IF NOT EXISTS stg.employee (
	id BIGINT NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NULL,
	department VARCHAR(120) NOT NULL,
	role VARCHAR(20) NULL,
	PRIMARY KEY("id")
);