FROM  --platform=linux/amd64 amazon/aws-glue-libs:glue_libs_4.0.0_image_01
USER root
WORKDIR /

RUN yum update -y
RUN yum install -y python3-pip
# RUN yum install -y python3-psycopg2
# RUN yum install -y  python3-dev
RUN yum upgrade -y
RUN yum install shadow-utils.x86_64 -y

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

RUN export PATH=$SPARK_HOME/bin:$PATH
RUN export PYTHONPATH=${PYTHONPATH}:/home/glue_user/workspace/jupyter_workspace/
CMD tail -f /dev/null